//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingApp.Application.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources_temp {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_temp() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BookingApp.Application.Properties.Resources-temp", typeof(Resources_temp).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        internal static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accommodation.
        /// </summary>
        internal static string Accommodation {
            get {
                return ResourceManager.GetString("Accommodation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accommodation location.
        /// </summary>
        internal static string AccommodationLocation {
            get {
                return ResourceManager.GetString("AccommodationLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accommodation name.
        /// </summary>
        internal static string AccommodationName {
            get {
                return ResourceManager.GetString("AccommodationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accommodation statistics.
        /// </summary>
        internal static string AccommodationStatistics {
            get {
                return ResourceManager.GetString("AccommodationStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accommodation type.
        /// </summary>
        internal static string AccommodationType {
            get {
                return ResourceManager.GetString("AccommodationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add comment.
        /// </summary>
        internal static string AddComment {
            get {
                return ResourceManager.GetString("AddComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add image.
        /// </summary>
        internal static string AddImage {
            get {
                return ResourceManager.GetString("AddImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional comment.
        /// </summary>
        internal static string AdditionalComment {
            get {
                return ResourceManager.GetString("AdditionalComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apartment.
        /// </summary>
        internal static string Apartment {
            get {
                return ResourceManager.GetString("Apartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel renovation.
        /// </summary>
        internal static string CancelRenovation {
            get {
                return ResourceManager.GetString("CancelRenovation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can you cancel the renovation.
        /// </summary>
        internal static string CanYouCancelTheRenovation {
            get {
                return ResourceManager.GetString("CanYouCancelTheRenovation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose an accommodation.
        /// </summary>
        internal static string ChooseAnAccommodation {
            get {
                return ResourceManager.GetString("ChooseAnAccommodation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose ending date.
        /// </summary>
        internal static string ChooseEndingDate {
            get {
                return ResourceManager.GetString("ChooseEndingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose starting date.
        /// </summary>
        internal static string ChooseStartingDate {
            get {
                return ResourceManager.GetString("ChooseStartingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose time period.
        /// </summary>
        internal static string ChooseTimePeriod {
            get {
                return ResourceManager.GetString("ChooseTimePeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleanliness.
        /// </summary>
        internal static string Cleanliness {
            get {
                return ResourceManager.GetString("Cleanliness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close accommodation.
        /// </summary>
        internal static string CloseAccommodation {
            get {
                return ResourceManager.GetString("CloseAccommodation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        internal static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current accommodation rating.
        /// </summary>
        internal static string CurrentAccommodationRating {
            get {
                return ResourceManager.GetString("CurrentAccommodationRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current guest rating.
        /// </summary>
        internal static string CurrentGuestRating {
            get {
                return ResourceManager.GetString("CurrentGuestRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current reservation timespan.
        /// </summary>
        internal static string CurrentReservationTimespan {
            get {
                return ResourceManager.GetString("CurrentReservationTimespan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark mode.
        /// </summary>
        internal static string DarkMode {
            get {
                return ResourceManager.GetString("DarkMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day before cancellation is final.
        /// </summary>
        internal static string DayBeforeCancellationIsFinal {
            get {
                return ResourceManager.GetString("DayBeforeCancellationIsFinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days before reservation is final.
        /// </summary>
        internal static string DaysBeforeReservationIsFinal {
            get {
                return ResourceManager.GetString("DaysBeforeReservationIsFinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detailed guest review.
        /// </summary>
        internal static string DetailedGuestReview {
            get {
                return ResourceManager.GetString("DetailedGuestReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detailed renovation view.
        /// </summary>
        internal static string DetailedRenovationView {
            get {
                return ResourceManager.GetString("DetailedRenovationView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detailed reservation view.
        /// </summary>
        internal static string DetailedReservationView {
            get {
                return ResourceManager.GetString("DetailedReservationView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date.
        /// </summary>
        internal static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🔍 Enter accommodation name....
        /// </summary>
        internal static string EnterAccommodationName {
            get {
                return ResourceManager.GetString("EnterAccommodationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📅 Enter comment.....
        /// </summary>
        internal static string EnterComment {
            get {
                return ResourceManager.GetString("EnterComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📅 Enter days before reservation is final....
        /// </summary>
        internal static string EnterDaysBeforeReservationIsFinal {
            get {
                return ResourceManager.GetString("EnterDaysBeforeReservationIsFinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📌Enter desired location....
        /// </summary>
        internal static string EnterDesiredLocation {
            get {
                return ResourceManager.GetString("EnterDesiredLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🧑Enter maximum number of guests....
        /// </summary>
        internal static string EnterMaximumNumberOfGuests {
            get {
                return ResourceManager.GetString("EnterMaximumNumberOfGuests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📅 Enter minimum number of days for reservations.
        /// </summary>
        internal static string EnterMinimumNumberOfDaysForReservation {
            get {
                return ResourceManager.GetString("EnterMinimumNumberOfDaysForReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $ Enter price....
        /// </summary>
        internal static string EnterPrice {
            get {
                return ResourceManager.GetString("EnterPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find available timespan.
        /// </summary>
        internal static string FindAvailableTimespan {
            get {
                return ResourceManager.GetString("FindAvailableTimespan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest feedback.
        /// </summary>
        internal static string GuestFeedback {
            get {
                return ResourceManager.GetString("GuestFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest number.
        /// </summary>
        internal static string GuestNumber {
            get {
                return ResourceManager.GetString("GuestNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest username.
        /// </summary>
        internal static string GuestUsername {
            get {
                return ResourceManager.GetString("GuestUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotel.
        /// </summary>
        internal static string Hotel {
            get {
                return ResourceManager.GetString("Hotel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to House.
        /// </summary>
        internal static string House {
            get {
                return ResourceManager.GetString("House", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images.
        /// </summary>
        internal static string Images {
            get {
                return ResourceManager.GetString("Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last cancellation day.
        /// </summary>
        internal static string LastCancellationDay {
            get {
                return ResourceManager.GetString("LastCancellationDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last renovation cancellation day.
        /// </summary>
        internal static string LastRenovationCancellationDay {
            get {
                return ResourceManager.GetString("LastRenovationCancellationDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light theme.
        /// </summary>
        internal static string LightTheme {
            get {
                return ResourceManager.GetString("LightTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum number of guests.
        /// </summary>
        internal static string MaximumNumberOfGuests {
            get {
                return ResourceManager.GetString("MaximumNumberOfGuests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum number of days for reservation.
        /// </summary>
        internal static string MinimumNumberOfDaysForReservation {
            get {
                return ResourceManager.GetString("MinimumNumberOfDaysForReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most popular month in year.
        /// </summary>
        internal static string MostPopularMonthInYear {
            get {
                return ResourceManager.GetString("MostPopularMonthInYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My courtesy.
        /// </summary>
        internal static string MyCourtesy {
            get {
                return ResourceManager.GetString("MyCourtesy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My reviews.
        /// </summary>
        internal static string MyReviews {
            get {
                return ResourceManager.GetString("MyReviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of cancelled reservations.
        /// </summary>
        internal static string NumberOfCancelledReservations {
            get {
                return ResourceManager.GetString("NumberOfCancelledReservations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of guests.
        /// </summary>
        internal static string NumberOfGuests {
            get {
                return ResourceManager.GetString("NumberOfGuests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of moved reservations.
        /// </summary>
        internal static string NumberOfMovedReservations {
            get {
                return ResourceManager.GetString("NumberOfMovedReservations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of renovation recommendations.
        /// </summary>
        internal static string NumberOfRenovationRecommendations {
            get {
                return ResourceManager.GetString("NumberOfRenovationRecommendations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of reservations.
        /// </summary>
        internal static string NumberOfReservations {
            get {
                return ResourceManager.GetString("NumberOfReservations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of reviews.
        /// </summary>
        internal static string NumberOfReviews {
            get {
                return ResourceManager.GetString("NumberOfReviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner.
        /// </summary>
        internal static string Owner {
            get {
                return ResourceManager.GetString("Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        internal static string Pending {
            get {
                return ResourceManager.GetString("Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price per night.
        /// </summary>
        internal static string PricePerNight {
            get {
                return ResourceManager.GetString("PricePerNight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject.
        /// </summary>
        internal static string Reject {
            get {
                return ResourceManager.GetString("Reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove image.
        /// </summary>
        internal static string RemoveImage {
            get {
                return ResourceManager.GetString("RemoveImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renovation end.
        /// </summary>
        internal static string RenovationEnd {
            get {
                return ResourceManager.GetString("RenovationEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renovation feedback.
        /// </summary>
        internal static string RenovationFeedback {
            get {
                return ResourceManager.GetString("RenovationFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renovation scheduling.
        /// </summary>
        internal static string RenovationScheduling {
            get {
                return ResourceManager.GetString("RenovationScheduling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renovation start.
        /// </summary>
        internal static string RenovationStart {
            get {
                return ResourceManager.GetString("RenovationStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renovation status.
        /// </summary>
        internal static string RenovationStatus {
            get {
                return ResourceManager.GetString("RenovationStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renovation urgency.
        /// </summary>
        internal static string RenovationUrgency {
            get {
                return ResourceManager.GetString("RenovationUrgency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requires renovation.
        /// </summary>
        internal static string RequiresRenovation {
            get {
                return ResourceManager.GetString("RequiresRenovation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rescheduling.
        /// </summary>
        internal static string Rescheduling {
            get {
                return ResourceManager.GetString("Rescheduling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation days.
        /// </summary>
        internal static string ReservationDays {
            get {
                return ResourceManager.GetString("ReservationDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation end.
        /// </summary>
        internal static string ReservationEnd {
            get {
                return ResourceManager.GetString("ReservationEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation rescheduling.
        /// </summary>
        internal static string ReservationRescheduling {
            get {
                return ResourceManager.GetString("ReservationRescheduling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation start.
        /// </summary>
        internal static string ReservationStart {
            get {
                return ResourceManager.GetString("ReservationStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation timespan.
        /// </summary>
        internal static string ReservationTimespan {
            get {
                return ResourceManager.GetString("ReservationTimespan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Respectfulness.
        /// </summary>
        internal static string Respectfulness {
            get {
                return ResourceManager.GetString("Respectfulness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reviewed.
        /// </summary>
        internal static string Reviewed {
            get {
                return ResourceManager.GetString("Reviewed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule a renovation.
        /// </summary>
        internal static string ScheduleARenovation {
            get {
                return ResourceManager.GetString("ScheduleARenovation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select month to display statistics.
        /// </summary>
        internal static string SelectMonthToDisplayStatistics {
            get {
                return ResourceManager.GetString("SelectMonthToDisplayStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select year to display statistics.
        /// </summary>
        internal static string SelectYearToDisplayStatistics {
            get {
                return ResourceManager.GetString("SelectYearToDisplayStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings and profile.
        /// </summary>
        internal static string SettingsAndProfile {
            get {
                return ResourceManager.GetString("SettingsAndProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date.
        /// </summary>
        internal static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wanted reservation timespan.
        /// </summary>
        internal static string WantedReservationTimespan {
            get {
                return ResourceManager.GetString("WantedReservationTimespan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year accommodation was most popular.
        /// </summary>
        internal static string YearAccommodationWasMostPopular {
            get {
                return ResourceManager.GetString("YearAccommodationWasMostPopular", resourceCulture);
            }
        }
    }
}
