//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BookingApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prihvati.
        /// </summary>
        internal static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smeštaj.
        /// </summary>
        internal static string Accommodation {
            get {
                return ResourceManager.GetString("Accommodation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lokacija smeštaja.
        /// </summary>
        internal static string AccommodationLocation {
            get {
                return ResourceManager.GetString("AccommodationLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naziv smeštaja.
        /// </summary>
        internal static string AccommodationName {
            get {
                return ResourceManager.GetString("AccommodationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smeštaji.
        /// </summary>
        internal static string Accommodations {
            get {
                return ResourceManager.GetString("Accommodations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistika o smeštajima.
        /// </summary>
        internal static string AccommodationStatistics {
            get {
                return ResourceManager.GetString("AccommodationStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip smeštaja.
        /// </summary>
        internal static string AccommodationType {
            get {
                return ResourceManager.GetString("AccommodationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj komentar?.
        /// </summary>
        internal static string AddComment {
            get {
                return ResourceManager.GetString("AddComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj sliku.
        /// </summary>
        internal static string AddImage {
            get {
                return ResourceManager.GetString("AddImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodavanje smeštaja.
        /// </summary>
        internal static string AddingAnAccommodation {
            get {
                return ResourceManager.GetString("AddingAnAccommodation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodatan komentar.
        /// </summary>
        internal static string AdditionalComment {
            get {
                return ResourceManager.GetString("AdditionalComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apartment.
        /// </summary>
        internal static string Apartman {
            get {
                return ResourceManager.GetString("Apartman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apartman.
        /// </summary>
        internal static string Apartment {
            get {
                return ResourceManager.GetString("Apartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to April.
        /// </summary>
        internal static string April {
            get {
                return ResourceManager.GetString("April", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avgust.
        /// </summary>
        internal static string August {
            get {
                return ResourceManager.GetString("August", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beograd.
        /// </summary>
        internal static string Belgrade {
            get {
                return ResourceManager.GetString("Belgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odustani.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to otkazanih rezervacija.
        /// </summary>
        internal static string CancelledReservationsLC {
            get {
                return ResourceManager.GetString("CancelledReservationsLC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otkaži renovaciju.
        /// </summary>
        internal static string CancelRenovation {
            get {
                return ResourceManager.GetString("CancelRenovation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Možete li otkazati renovaciju?.
        /// </summary>
        internal static string CanYouCancelTheRenovation {
            get {
                return ResourceManager.GetString("CanYouCancelTheRenovation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izaberi smeštaj.
        /// </summary>
        internal static string ChooseAnAccommodation {
            get {
                return ResourceManager.GetString("ChooseAnAccommodation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izaberite kraj.
        /// </summary>
        internal static string ChooseEndingDate {
            get {
                return ResourceManager.GetString("ChooseEndingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izaberite početak.
        /// </summary>
        internal static string ChooseStartingDate {
            get {
                return ResourceManager.GetString("ChooseStartingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izaberite broj dana.
        /// </summary>
        internal static string ChooseTimePeriod {
            get {
                return ResourceManager.GetString("ChooseTimePeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izaberite tip.
        /// </summary>
        internal static string ChooseType {
            get {
                return ResourceManager.GetString("ChooseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Čistoća.
        /// </summary>
        internal static string Cleanliness {
            get {
                return ResourceManager.GetString("Cleanliness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zatvori smeštaj.
        /// </summary>
        internal static string CloseAccommodation {
            get {
                return ResourceManager.GetString("CloseAccommodation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Komentar.
        /// </summary>
        internal static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potvrdi.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trenutna ocena smeštaja.
        /// </summary>
        internal static string CurrentAccommodationRating {
            get {
                return ResourceManager.GetString("CurrentAccommodationRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trenutna ocena gosta.
        /// </summary>
        internal static string CurrentGuestRating {
            get {
                return ResourceManager.GetString("CurrentGuestRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trenutni dani rezervacije.
        /// </summary>
        internal static string CurrentReservationTimespan {
            get {
                return ResourceManager.GetString("CurrentReservationTimespan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamna tema.
        /// </summary>
        internal static string DarkMode {
            get {
                return ResourceManager.GetString("DarkMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dan kada je rezervacija finalizirana.
        /// </summary>
        internal static string DayBeforeCancellationIsFinal {
            get {
                return ResourceManager.GetString("DayBeforeCancellationIsFinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dan.
        /// </summary>
        internal static string DayLC {
            get {
                return ResourceManager.GetString("DayLC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj dana pred finalizaciju rezervacije.
        /// </summary>
        internal static string DaysBeforeReservationIsFinal {
            get {
                return ResourceManager.GetString("DaysBeforeReservationIsFinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dan(a).
        /// </summary>
        internal static string DaysLC {
            get {
                return ResourceManager.GetString("DaysLC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decembar.
        /// </summary>
        internal static string December {
            get {
                return ResourceManager.GetString("December", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detaljan prikaz smeštaja.
        /// </summary>
        internal static string DetailedAccommodationView {
            get {
                return ResourceManager.GetString("DetailedAccommodationView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detaljna ocena gosta.
        /// </summary>
        internal static string DetailedGuestReview {
            get {
                return ResourceManager.GetString("DetailedGuestReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detaljan prikaz renovacije.
        /// </summary>
        internal static string DetailedRenovationView {
            get {
                return ResourceManager.GetString("DetailedRenovationView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detaljan prikaz rezervacije.
        /// </summary>
        internal static string DetailedReservationView {
            get {
                return ResourceManager.GetString("DetailedReservationView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ne, ne zahteva..
        /// </summary>
        internal static string DoesNotRequireRenovation {
            get {
                return ResourceManager.GetString("DoesNotRequireRenovation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Da, zahteva..
        /// </summary>
        internal static string DoesRequireRenovation {
            get {
                return ResourceManager.GetString("DoesRequireRenovation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Krajnji datum.
        /// </summary>
        internal static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🔍 Ukucaj naziv smeštaja....
        /// </summary>
        internal static string EnterAccommodationName {
            get {
                return ResourceManager.GetString("EnterAccommodationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📅 Ukucaj željeni komentar....
        /// </summary>
        internal static string EnterComment {
            get {
                return ResourceManager.GetString("EnterComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📅 Ukucaj broj dana pred finalizaciju rezervacije....
        /// </summary>
        internal static string EnterDaysBeforeReservationIsFinal {
            get {
                return ResourceManager.GetString("EnterDaysBeforeReservationIsFinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📌Ukucaj naziv lokacije....
        /// </summary>
        internal static string EnterDesiredLocation {
            get {
                return ResourceManager.GetString("EnterDesiredLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🧑Ukucaj najveći broj gostiju....
        /// </summary>
        internal static string EnterMaximumNumberOfGuests {
            get {
                return ResourceManager.GetString("EnterMaximumNumberOfGuests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📅 Ukucaj najmanji broj dana za rezervaciju....
        /// </summary>
        internal static string EnterMinimumNumberOfDaysForReservation {
            get {
                return ResourceManager.GetString("EnterMinimumNumberOfDaysForReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $ Ukucaj cenu....
        /// </summary>
        internal static string EnterPrice {
            get {
                return ResourceManager.GetString("EnterPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Februar.
        /// </summary>
        internal static string February {
            get {
                return ResourceManager.GetString("February", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pronađi termin.
        /// </summary>
        internal static string FindAvailableTimespan {
            get {
                return ResourceManager.GetString("FindAvailableTimespan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Završena.
        /// </summary>
        internal static string Finished {
            get {
                return ResourceManager.GetString("Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OD:.
        /// </summary>
        internal static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recenzija od gosta.
        /// </summary>
        internal static string GuestFeedback {
            get {
                return ResourceManager.GetString("GuestFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gost.
        /// </summary>
        internal static string GuestLC {
            get {
                return ResourceManager.GetString("GuestLC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj gostiju.
        /// </summary>
        internal static string GuestNumber {
            get {
                return ResourceManager.GetString("GuestNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oceni gosta.
        /// </summary>
        internal static string GuestRating {
            get {
                return ResourceManager.GetString("GuestRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocene gostiju.
        /// </summary>
        internal static string GuestReviews {
            get {
                return ResourceManager.GetString("GuestReviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recenzije od gostiju.
        /// </summary>
        internal static string GuestsFeedback {
            get {
                return ResourceManager.GetString("GuestsFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gost(iju).
        /// </summary>
        internal static string GuestsLC {
            get {
                return ResourceManager.GetString("GuestsLC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisničko ime gosta.
        /// </summary>
        internal static string GuestUsername {
            get {
                return ResourceManager.GetString("GuestUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotel.
        /// </summary>
        internal static string Hotel {
            get {
                return ResourceManager.GetString("Hotel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kuća.
        /// </summary>
        internal static string House {
            get {
                return ResourceManager.GetString("House", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slike.
        /// </summary>
        internal static string Images {
            get {
                return ResourceManager.GetString("Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Januar.
        /// </summary>
        internal static string January {
            get {
                return ResourceManager.GetString("January", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jul.
        /// </summary>
        internal static string July {
            get {
                return ResourceManager.GetString("July", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jun.
        /// </summary>
        internal static string June {
            get {
                return ResourceManager.GetString("June", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shack.
        /// </summary>
        internal static string Koliba {
            get {
                return ResourceManager.GetString("Koliba", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to House.
        /// </summary>
        internal static string Kuća {
            get {
                return ResourceManager.GetString("Kuća", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poslednji dan za otkazivanje.
        /// </summary>
        internal static string LastCancellationDay {
            get {
                return ResourceManager.GetString("LastCancellationDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poslednja renovacija:.
        /// </summary>
        internal static string LastRenovation {
            get {
                return ResourceManager.GetString("LastRenovation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poslednji dan za otkaz renovacije.
        /// </summary>
        internal static string LastRenovationCancellationDay {
            get {
                return ResourceManager.GetString("LastRenovationCancellationDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Svetla tema.
        /// </summary>
        internal static string LightTheme {
            get {
                return ResourceManager.GetString("LightTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lokacija.
        /// </summary>
        internal static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izloguj se.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Napravi smeštaj.
        /// </summary>
        internal static string MakeAccommodation {
            get {
                return ResourceManager.GetString("MakeAccommodation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mart.
        /// </summary>
        internal static string March {
            get {
                return ResourceManager.GetString("March", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Najveći broj gostiju.
        /// </summary>
        internal static string MaximumNumberOfGuests {
            get {
                return ResourceManager.GetString("MaximumNumberOfGuests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maj.
        /// </summary>
        internal static string May {
            get {
                return ResourceManager.GetString("May", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Najmanji broj dana rezervacije.
        /// </summary>
        internal static string MinimumNumberOfDaysForReservation {
            get {
                return ResourceManager.GetString("MinimumNumberOfDaysForReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Najpopularniji mesec.
        /// </summary>
        internal static string MostPopularMonth {
            get {
                return ResourceManager.GetString("MostPopularMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Najpopularniji mesec u godini:.
        /// </summary>
        internal static string MostPopularMonthInYear {
            get {
                return ResourceManager.GetString("MostPopularMonthInYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Najpopularnija godina.
        /// </summary>
        internal static string MostPopularYear {
            get {
                return ResourceManager.GetString("MostPopularYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pomerenih rezervacija.
        /// </summary>
        internal static string MovedReservationsLC {
            get {
                return ResourceManager.GetString("MovedReservationsLC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moje poštovanje.
        /// </summary>
        internal static string MyCourtesy {
            get {
                return ResourceManager.GetString("MyCourtesy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moje recenzije.
        /// </summary>
        internal static string MyReviews {
            get {
                return ResourceManager.GetString("MyReviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nikada renovirana!.
        /// </summary>
        internal static string NeverBeenRenovated {
            get {
                return ResourceManager.GetString("NeverBeenRenovated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nema rezervacija za datu godinu..
        /// </summary>
        internal static string NoReservationsInYear {
            get {
                return ResourceManager.GetString("NoReservationsInYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obaveštenja.
        /// </summary>
        internal static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novembar.
        /// </summary>
        internal static string November {
            get {
                return ResourceManager.GetString("November", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj otkazanih rezervacija:.
        /// </summary>
        internal static string NumberOfCancelledReservations {
            get {
                return ResourceManager.GetString("NumberOfCancelledReservations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj gostiju.
        /// </summary>
        internal static string NumberOfGuests {
            get {
                return ResourceManager.GetString("NumberOfGuests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj pomerenih rezervacija:.
        /// </summary>
        internal static string NumberOfMovedReservations {
            get {
                return ResourceManager.GetString("NumberOfMovedReservations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj preporuka za renovaciju:.
        /// </summary>
        internal static string NumberOfRenovationRecommendations {
            get {
                return ResourceManager.GetString("NumberOfRenovationRecommendations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj rezervacija:.
        /// </summary>
        internal static string NumberOfReservations {
            get {
                return ResourceManager.GetString("NumberOfReservations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj ocena.
        /// </summary>
        internal static string NumberOfReviews {
            get {
                return ResourceManager.GetString("NumberOfReviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oktobar.
        /// </summary>
        internal static string October {
            get {
                return ResourceManager.GetString("October", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U procesu.
        /// </summary>
        internal static string Ongoing {
            get {
                return ResourceManager.GetString("Ongoing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vlasnik.
        /// </summary>
        internal static string Owner {
            get {
                return ResourceManager.GetString("Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VLASNIK.
        /// </summary>
        internal static string OwnerUC {
            get {
                return ResourceManager.GetString("OwnerUC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF izveštaj.
        /// </summary>
        internal static string PDFReport {
            get {
                return ResourceManager.GetString("PDFReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neocenjeni.
        /// </summary>
        internal static string Pending {
            get {
                return ResourceManager.GetString("Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cena.
        /// </summary>
        internal static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cena noćenja ($).
        /// </summary>
        internal static string PricePerNight {
            get {
                return ResourceManager.GetString("PricePerNight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odbij.
        /// </summary>
        internal static string Reject {
            get {
                return ResourceManager.GetString("Reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obriši sliku.
        /// </summary>
        internal static string RemoveImage {
            get {
                return ResourceManager.GetString("RemoveImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kraj renovacije.
        /// </summary>
        internal static string RenovationEnd {
            get {
                return ResourceManager.GetString("RenovationEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Komentar renovacije.
        /// </summary>
        internal static string RenovationFeedback {
            get {
                return ResourceManager.GetString("RenovationFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RENOVACIJA NIJE POTREBNA!.
        /// </summary>
        internal static string RenovationNotRequired {
            get {
                return ResourceManager.GetString("RenovationNotRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to preporuka za renovaciju.
        /// </summary>
        internal static string RenovationRecommendationsLC {
            get {
                return ResourceManager.GetString("RenovationRecommendationsLC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RENOVACIJA POTREBNA!.
        /// </summary>
        internal static string RenovationRequired {
            get {
                return ResourceManager.GetString("RenovationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renovacije.
        /// </summary>
        internal static string Renovations {
            get {
                return ResourceManager.GetString("Renovations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zakazivanje renovacije.
        /// </summary>
        internal static string RenovationScheduling {
            get {
                return ResourceManager.GetString("RenovationScheduling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Početak renovacije.
        /// </summary>
        internal static string RenovationStart {
            get {
                return ResourceManager.GetString("RenovationStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status renovacije.
        /// </summary>
        internal static string RenovationStatus {
            get {
                return ResourceManager.GetString("RenovationStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Urgentnost renovacije.
        /// </summary>
        internal static string RenovationUrgency {
            get {
                return ResourceManager.GetString("RenovationUrgency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zahteva renovaciju.
        /// </summary>
        internal static string RequiresRenovation {
            get {
                return ResourceManager.GetString("RequiresRenovation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pomeri rezervaciju.
        /// </summary>
        internal static string RescheduleReservation {
            get {
                return ResourceManager.GetString("RescheduleReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pomeranje.
        /// </summary>
        internal static string Rescheduling {
            get {
                return ResourceManager.GetString("Rescheduling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj dana rezervacije.
        /// </summary>
        internal static string ReservationDays {
            get {
                return ResourceManager.GetString("ReservationDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kraj rezervacije.
        /// </summary>
        internal static string ReservationEnd {
            get {
                return ResourceManager.GetString("ReservationEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pomeranje rezervacije.
        /// </summary>
        internal static string ReservationRescheduling {
            get {
                return ResourceManager.GetString("ReservationRescheduling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rezervacije.
        /// </summary>
        internal static string Reservations {
            get {
                return ResourceManager.GetString("Reservations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rezervacija.
        /// </summary>
        internal static string ReservationsLC {
            get {
                return ResourceManager.GetString("ReservationsLC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Početak rezervacije.
        /// </summary>
        internal static string ReservationStart {
            get {
                return ResourceManager.GetString("ReservationStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vremenski period.
        /// </summary>
        internal static string ReservationTimespan {
            get {
                return ResourceManager.GetString("ReservationTimespan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poštovanje.
        /// </summary>
        internal static string Respectfulness {
            get {
                return ResourceManager.GetString("Respectfulness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocenjieni.
        /// </summary>
        internal static string Reviewed {
            get {
                return ResourceManager.GetString("Reviewed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ocena.
        /// </summary>
        internal static string ReviewsLC {
            get {
                return ResourceManager.GetString("ReviewsLC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zakaži renovaciju.
        /// </summary>
        internal static string ScheduleARenovation {
            get {
                return ResourceManager.GetString("ScheduleARenovation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zakaži renovaciju.
        /// </summary>
        internal static string ScheduleRenovation {
            get {
                return ResourceManager.GetString("ScheduleRenovation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izaberi mesec za prikaz statistika.
        /// </summary>
        internal static string SelectMonthToDisplayStatistics {
            get {
                return ResourceManager.GetString("SelectMonthToDisplayStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izaberi godinu za prikaz statistika.
        /// </summary>
        internal static string SelectYearToDisplayStatistics {
            get {
                return ResourceManager.GetString("SelectYearToDisplayStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Septembar.
        /// </summary>
        internal static string September {
            get {
                return ResourceManager.GetString("September", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Srbija.
        /// </summary>
        internal static string Serbia {
            get {
                return ResourceManager.GetString("Serbia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podešavanja.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podešavanja i profil.
        /// </summary>
        internal static string SettingsAndProfile {
            get {
                return ResourceManager.GetString("SettingsAndProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Koliba.
        /// </summary>
        internal static string Shack {
            get {
                return ResourceManager.GetString("Shack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Početni datum.
        /// </summary>
        internal static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistike.
        /// </summary>
        internal static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status pomeranja rezervacije.
        /// </summary>
        internal static string StatusOfWantedReservationTimespan {
            get {
                return ResourceManager.GetString("StatusOfWantedReservationTimespan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUPER VLASNIK.
        /// </summary>
        internal static string SuperOwnerUC {
            get {
                return ResourceManager.GetString("SuperOwnerUC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pritisnite ovde.
        /// </summary>
        internal static string TapHere {
            get {
                return ResourceManager.GetString("TapHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DO:.
        /// </summary>
        internal static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip rezervacije.
        /// </summary>
        internal static string TypeOfReservation {
            get {
                return ResourceManager.GetString("TypeOfReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nadolazeća.
        /// </summary>
        internal static string Upcoming {
            get {
                return ResourceManager.GetString("Upcoming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisničko ime.
        /// </summary>
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hteli dani rezervacije.
        /// </summary>
        internal static string WantedReservationTimespan {
            get {
                return ResourceManager.GetString("WantedReservationTimespan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Godina kada je smeštaj bio najpopularniji:.
        /// </summary>
        internal static string YearAccommodationWasMostPopular {
            get {
                return ResourceManager.GetString("YearAccommodationWasMostPopular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Da, možete otkazati..
        /// </summary>
        internal static string YouCanCancel {
            get {
                return ResourceManager.GetString("YouCanCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ne, ne možete otkazati..
        /// </summary>
        internal static string YouCantCancel {
            get {
                return ResourceManager.GetString("YouCantCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imate neocenjene goste. Pritisnite ispod da bi ste ih ocenili..
        /// </summary>
        internal static string YouHaveUnreviewedGuests {
            get {
                return ResourceManager.GetString("YouHaveUnreviewedGuests", resourceCulture);
            }
        }
    }
}
